### ISSUE TITLE
Container fails to start

### ISSUE THREAD

**Issue by wjbeckett** [si0972/si0972-templates#1]
Looks like the latest commit breaks the containers. After a fresh build, the container doesn't start.

The error in the log is something like can't find directory for the new log dir's.

If I use your older 'docker-templates' repo it works fine.

The main difference ce I can see is that the old repo doesn't have the log directories.

**Comment by wjbeckett** [comment]
It's this path in particular that fails.

Container Path: /sickbeard_mp4_automator/info.log

**Comment by si0972** [comment]
This is normal behaviour; it happens because UnRaid looks for a file that doesn’t exist. It’s just empty text files. I haven’t looked at a way to generate them yet. A fix would be to make empty text files on your array.

**Comment by wjbeckett** [comment]
Ah okay no problem. Thanks for the tip!

**Comment by wjbeckett** [comment]
Still getting an issue when trying to start the container with empty text files.

```
container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:53: mounting \\\"/mnt/user/appdata/mp4_automator\\\" to rootfs \\\"/var/lib/docker/btrfs/subvolumes/f94aa3e49cb07172f260db181d5ac6f4b8a2491a6136a5dd41f9c9a54a29e76f\\\" at \\\"/var/lib/docker/btrfs/subvolumes/f94aa3e49cb07172f260db181d5ac6f4b8a2491a6136a5dd41f9c9a54a29e76f/sickbeard_mp4_automator/info.log\\\" caused \\\"not a directory\\\"\""
```

**Comment by si0972** [comment]
Can i get a screenshot of the paths you are putting in?

**Comment by wjbeckett** [comment]
Yeah sure.
https://photos.app.goo.gl/BdvxazX4RWxuIEaE2

**Comment by si0972** [comment]
Yea, both log files, and autoprocess need to point to a file, not a directory

**Comment by wjbeckett** [comment]
Yep, but if I put a file location  there, it creates a dir

**Comment by si0972** [comment]
![2017-09-30_21-31-24](https://user-images.githubusercontent.com/7110194/31050715-6e9a2f94-a653-11e7-9a51-37540a7f1715.png)
This is how mine is setup.

**Comment by si0972** [comment]
![2017-10-01_02-51-06](https://user-images.githubusercontent.com/7110194/31050720-881703c0-a653-11e7-9ef3-bb8829f7fa29.png)
This is how mine is.

**Comment by wjbeckett** [comment]
Alright. Thanks. I'll give it another go.
